### ISSUE TITLE
file structure problem 

### ISSUE THREAD

**Issue by harryhoch** [DeepPhe/DeepPhe#21]
fresh checkout, mvn clean; mvn package gets a test failure 

org.apache.uima.resource.ResourceInitializationException: Invalid value for parameter "InputDirectory" in component "org.healthnlp.deepphe.uima.cr.FHIRCollectionReader" -- directory "/Users/harry/Box Sync/research/projects/deepphe/dev/DeepPhe/deepphe-uima/../data/sample/output/FHIR" does not exist.

said directory does not in fact exist. Manual creation of directory fixes problem. Should probably ensure that the directory exists before trying output and create it if not.

**Comment by seanfinan** [comment]
File.mkdirs() (or FileSystem equivalent) should always be used for output directories, but it looks like this one is an input directory?  One thing that java often has problems with, though it may recently have been fixed, is relative path specification with dots.  What happens if you try "/Users/harry/Box Sync/research/projects/deepphe/dev/DeepPhe/data/sample/output/FHIR" ?

**Comment by harryhoch** [comment]
1. Why does it look like its an input directory?  
2. Regarding the path spec, I don't see a good way to change it without modifying the code...

**Comment by seanfinan** [comment]
1.  From the error message: " Invalid value for parameter "InputDirectory" "
2.  I think that Eugene is handling it.  I didn't realize that the "parameter" was hardcoded
No worries, thanks

**Comment by harryhoch** [comment]
oh, I missed that. Just saw "output" in the path.

**Comment by seanfinan** [comment]
Fixed
